name: "build"
on:                                                                                                                                                                                                    
  push:                                                                                                                                                                                                
    branches:                                                                                                                                                                                          
      - master 
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: "actions/checkout@v2"
    - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
    - run: |
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi build-essential git python3-pip
    - run: "pip3 install -U git+https://github.com/TuxSH/firmtool.git"
    - run: "env CC=arm-none-eabi-gcc make"
    - uses: "actions/upload-artifact@v7.0.1"
      with:
        path: firm_linux_loader.firm
        archive: false
